version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
platform:
- Any CPU
- x86
- x64
- ARM
- iPhone
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
xamarin:
  email: vjvdewet@sharklasers.com
  password:
    secure: 03Rko6eYbwtkcXxrSRGKig==
  android: true
  ios: true
before_build:
- cmd: >-
    appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd

    IF "%PLATFORM%"=="x64" set NUGET_RESTORE=1

    IF "%PLATFORM%"=="x86" set NUGET_RESTORE=1

    IF "%PLATFORM%"=="ARM" set NUGET_RESTORE=1

    IF "%NUGET_RESTORE%"=="1" nuget-restore src\CodeCutterUK.AppVeyor.Example.sln
build:
  project: src\CodeCutterUK.AppVeyor.Example.sln
  parallel: true
  verbosity: detailed
deploy: off
